function [steadyWindow, diagnostics] = ...
    determineQuasiSteadyWindow(cfg, driverData, triggerData, dataData)
%DETERMINEQUASISTEADYWINDOW Detect a quasi-steady PCB flow interval.
%
% All input time vectors must already use relative time in seconds.
% PCB onset depends on post-trigger PCB fluctuations and persistence only.
% Driver-flat windows are calculated independently for reporting.


    validateInputData(driverData, 'driverData');
    validateInputData(triggerData, 'triggerData');
    validateInputData(dataData, 'dataData');

    steadyWindow = struct( ...
        'time', [NaN NaN], ...
        'startTime', NaN, ...
        'endTime', NaN, ...
        'driverFlatWindows', emptyWindowArray(), ...
        'driverStateTime', [], ...
        'driverState', strings(0, 1), ...
        'pcbStateTime', [], ...
        'pcbState', strings(0, 1), ...
        'pcbFluctuationRatio', []);

    diagnostics = struct( ...
        'triggerTime', NaN, ...
        'driverStartTime', NaN, ...
        'driverEndTime', NaN, ...
        'driverFlatWindows', emptyWindowArray(), ...
        'driverStateTime', [], ...
        'driverState', strings(0, 1), ...
        'pcbChannel', "", ...
        'pcbReferenceLevel', NaN, ...
        'pcbFirstValidStart', NaN, ...
        'pcbFirstUnstart', NaN, ...
        'pcbStartTime', NaN, ...
        'pcbEndTime', NaN, ...
        'startCandidates', [NaN NaN NaN], ...
        'endCandidates', [NaN NaN]);

    triggerTime = detectTriggerThreshold( ...
        triggerData, ...
        cfg);

    diagnostics.triggerTime = triggerTime;

    [driverStartTime, driverEndTime, driverFlatWindows] = ...
        detectFlatDriverWindow( ...
            driverData, ...
            triggerTime, ...
            cfg);

    diagnostics.driverStartTime = driverStartTime;
    diagnostics.driverEndTime = driverEndTime;
    diagnostics.driverFlatWindows = driverFlatWindows;
    steadyWindow.driverFlatWindows = driverFlatWindows;

    [driverStateTime, driverState] = ...
        classifyDriverState( ...
            driverData, ...
            cfg);

    diagnostics.driverStateTime = driverStateTime;
    diagnostics.driverState = driverState;
    steadyWindow.driverStateTime = driverStateTime;
    steadyWindow.driverState = driverState;

    [pcbWindow, pcbDiagnostics] = ...
        detectPcbFlowWindow( ...
            dataData, ...
            triggerTime, ...
            cfg);

    diagnostics.pcbChannel = pcbDiagnostics.channel;
    diagnostics.pcbReferenceLevel = ...
        pcbDiagnostics.referenceLevel;
    diagnostics.pcbFirstValidStart = ...
        pcbDiagnostics.firstValidStart;
    diagnostics.pcbFirstUnstart = ...
        pcbDiagnostics.firstUnstart;
    diagnostics.pcbStartTime = pcbWindow.startTime;
    diagnostics.pcbEndTime = pcbWindow.endTime;
    diagnostics.startCandidates = [ ...
        triggerTime, ...
        driverStartTime, ...
        pcbWindow.startTime];
    diagnostics.endCandidates = [ ...
        driverEndTime, ...
        pcbWindow.endTime];

    steadyWindow.pcbStateTime = pcbDiagnostics.time;
    steadyWindow.pcbState = pcbDiagnostics.state;
    steadyWindow.pcbFluctuationRatio = ...
        pcbDiagnostics.fluctuationRatio;

    steadyWindow.startTime = pcbWindow.startTime;
    steadyWindow.endTime = pcbWindow.endTime;
    steadyWindow.time = [ ...
        pcbWindow.startTime, ...
        pcbWindow.endTime];

end

function validateInputData(data, name)

    requiredFields = ["channels", "time", "signal", "samplingRate"];

    for fieldIndex = 1:numel(requiredFields)
        fieldName = requiredFields(fieldIndex);

        if ~isfield(data, fieldName)
            error( ...
                'determineQuasiSteadyWindow:MissingField', ...
                '%s must contain the field "%s".', ...
                name, fieldName);
        end
    end

    if numel(data.time) ~= numel(data.signal)
        error( ...
            'determineQuasiSteadyWindow:SizeMismatch', ...
            '%s.time and %s.signal must have the same number of channels.', ...
            name, name);
    end

    for channelIndex = 1:numel(data.time)
        time = data.time{channelIndex};

        if isempty(time)
            continue
        end

        time = time(:);

        if numel(time) < 2 || ...
                any(~isfinite(time)) || ...
                any(diff(time) <= 0)
            error( ...
                'determineQuasiSteadyWindow:InvalidTime', ...
                '%s.time{%d} must contain finite, strictly increasing samples.', ...
                name, channelIndex);
        end
    end

end

function triggerTime = detectTriggerThreshold(triggerData, cfg)

    triggerTime = NaN;

    if isempty(triggerData.signal) || ...
            isempty(triggerData.time) || ...
            isempty(triggerData.signal{1}) || ...
            isempty(triggerData.time{1})
        return
    end

    signal = triggerData.signal{1};
    time = triggerData.time{1};

    signal = signal(:);
    time = time(:);

    triggerThreshold = getTimingValue( ...
        cfg, ...
        'triggerThreshold', ...
        2.5);

    triggerHysteresis = getTimingValue( ...
        cfg, ...
        'triggerHysteresis', ...
        2.3);

    triggerHoldTime = getTimingValue( ...
        cfg, ...
        'triggerHoldTime', ...
        0.002);

    candidateIndices = find(signal >= triggerThreshold);

    for candidatePosition = 1:numel(candidateIndices)

        candidateIndex = candidateIndices(candidatePosition);

        for stableIndex = candidateIndex:numel(signal)
            holdEndIndex = find( ...
                time >= time(stableIndex) + triggerHoldTime, ...
                1);

            if isempty(holdEndIndex)
                break
            end

            heldSignal = signal(stableIndex:holdEndIndex);

            if all(heldSignal >= triggerHysteresis)
                triggerTime = time(candidateIndex);
                return
            end
        end
    end

end

function [flatStartTime, flatEndTime, flatWindows] = ...
    detectFlatDriverWindow(driverData, triggerTime, cfg)

    flatStartTime = NaN;
    flatEndTime = NaN;
    flatWindows = emptyWindowArray();

    if ~isfinite(triggerTime)
        return
    end

    signal = driverData.signal{1};
    time = driverData.time{1};

    if isempty(signal) || isempty(time)
        return
    end

    signal = signal(:);
    time = time(:);

    flatWindow = getTimingValue( ...
        cfg, ...
        'driverFlatWindow', ...
        0.050);

    flatHoldTime = getTimingValue( ...
        cfg, ...
        'driverFlatHoldTime', ...
        0.050);

    slopeThreshold = getTimingValue( ...
        cfg, ...
        'driverFlatSlopeThreshold', ...
        0.05);

    noiseThreshold = getTimingValue( ...
        cfg, ...
        'driverFlatNoiseThreshold', ...
        0.010);

    evaluationInterval = getTimingValue( ...
        cfg, ...
        'driverFlatEvaluationInterval', ...
        0.001);

    sampleInterval = median(diff(time), 'omitnan');
    evaluationStep = max(1, round(evaluationInterval / sampleInterval));
    evaluationIndices = 1:evaluationStep:numel(time);

    time = time(evaluationIndices);
    signal = signal(evaluationIndices);

    searchStartTime = triggerTime;

    candidateStartIndex = find( ...
        time >= searchStartTime, ...
        1);

    if isempty(candidateStartIndex)
        return
    end

    flatMask = false(size(time));
    firstWindowEndIndex = find( ...
        time >= time(candidateStartIndex) + flatWindow, ...
        1);

    if isempty(firstWindowEndIndex)
        return
    end

    for windowEndIndex = firstWindowEndIndex:numel(time)

        windowEndTime = time(windowEndIndex);
        windowStartTime = windowEndTime - flatWindow;

        windowStartIndex = find( ...
            time >= windowStartTime, ...
            1);

        windowIndices = windowStartIndex:windowEndIndex;

        if numel(windowIndices) < 3
            continue
        end

        windowTime = time(windowIndices);
        windowSignal = signal(windowIndices);

        fitCoefficients = polyfit( ...
            windowTime - windowEndTime, ...
            windowSignal, ...
            1);

        fittedSignal = polyval( ...
            fitCoefficients, ...
            windowTime - windowEndTime);

        localSlope = fitCoefficients(1);
        localResidual = windowSignal - fittedSignal;
        localNoise = std(localResidual, 'omitnan');

        flatMask(windowEndIndex) = ...
            isfinite(localSlope) && ...
            isfinite(localNoise) && ...
            abs(localSlope) <= slopeThreshold && ...
            localNoise <= noiseThreshold;
    end

    runStartIndices = find( ...
        flatMask & ...
        [true; ~flatMask(1:end-1)]);

    runEndIndices = find( ...
        flatMask & ...
        [~flatMask(2:end); true]);

    candidateFlatWindows = repmat(struct( ...
        'startTime', NaN, 'endTime', NaN), numel(runStartIndices), 1);
    acceptedWindowCount = 0;

    for runIndex = 1:numel(runStartIndices)

        runStartIndex = runStartIndices(runIndex);
        runEndIndex = runEndIndices(runIndex);

        if time(runEndIndex) - time(runStartIndex) < flatHoldTime
            continue
        end

        windowStartTime = max( ...
            triggerTime, ...
            time(runStartIndex) - flatWindow);

        acceptedWindowCount = acceptedWindowCount + 1;
        candidateFlatWindows(acceptedWindowCount).startTime = windowStartTime;
        candidateFlatWindows(acceptedWindowCount).endTime = time(runEndIndex);
    end

    flatWindows = candidateFlatWindows(1:acceptedWindowCount);

    if isempty(flatWindows)
        return
    end

    flatStartTime = flatWindows(1).startTime;
    flatEndTime = flatWindows(end).endTime;

end

function windows = emptyWindowArray()

    windows = struct( ...
        'startTime', {}, ...
        'endTime', {});
end

function value = getTimingValue(cfg, fieldName, defaultValue)

    value = defaultValue;

    if isfield(cfg, 'timing') && ...
            isfield(cfg.timing, fieldName) && ...
            ~isempty(cfg.timing.(fieldName))

        value = cfg.timing.(fieldName);
    end

end

function [stateTime, stateLabels] = ...
    classifyDriverState(driverData, cfg)

    stateTime = [];
    stateLabels = strings(0, 1);

    signal = driverData.signal{1};
    time = driverData.time{1};

    if isempty(signal) || isempty(time)
        return
    end

    signal = signal(:);
    time = time(:);

    evaluationInterval = getTimingValue( ...
        cfg, ...
        'driverFlatEvaluationInterval', ...
        0.001);

    flatWindow = getTimingValue( ...
        cfg, ...
        'driverFlatWindow', ...
        0.050);

    flatSlopeThreshold = getTimingValue( ...
        cfg, ...
        'driverFlatSlopeThreshold', ...
        0.10);

    descendingSlopeThreshold = getTimingValue( ...
        cfg, ...
        'driverDescendingSlopeThreshold', ...
        0.10);

    noiseThreshold = getTimingValue( ...
        cfg, ...
        'driverFlatNoiseThreshold', ...
        0.010);

    sampleInterval = median(diff(time), 'omitnan');
    evaluationStep = max( ...
        1, ...
        round(evaluationInterval / sampleInterval));

    evaluationIndices = 1:evaluationStep:numel(time);
    stateTime = time(evaluationIndices);
    stateLabels = repmat("other", size(stateTime));

    for stateIndex = 1:numel(evaluationIndices)

        currentIndex = evaluationIndices(stateIndex);

        if time(currentIndex) - time(1) < flatWindow
            continue
        end

        windowStartTime = time(currentIndex) - flatWindow;
        windowStartIndex = find(time >= windowStartTime, 1);
        windowIndices = windowStartIndex:currentIndex;

        windowTime = time(windowIndices);
        windowSignal = signal(windowIndices);

        fitCoefficients = polyfit( ...
            windowTime - time(currentIndex), ...
            windowSignal, ...
            1);

        fittedSignal = polyval( ...
            fitCoefficients, ...
            windowTime - time(currentIndex));

        localSlope = fitCoefficients(1);
        localNoise = std( ...
            windowSignal - fittedSignal, ...
            'omitnan');

        if ~isfinite(localSlope) || ...
                ~isfinite(localNoise) || ...
                localNoise > noiseThreshold
            continue
        end

        if abs(localSlope) <= flatSlopeThreshold
            stateLabels(stateIndex) = "flat";
        elseif localSlope <= -descendingSlopeThreshold
            stateLabels(stateIndex) = "descending";
        end
    end
end

function [pcbWindow, diagnostics] = ...
    detectPcbFlowWindow(dataData, triggerTime, cfg)

    pcbWindow = struct( ...
        'startTime', NaN, ...
        'endTime', NaN, ...
        'valid', false);

    diagnostics = struct( ...
        'channel', "", ...
        'time', [], ...
        'fluctuationLevel', [], ...
        'fluctuationRatio', [], ...
        'state', strings(0, 1), ...
        'referenceLevel', NaN, ...
        'firstValidStart', NaN, ...
        'firstUnstart', NaN);

    channelName = getTimingValue( ...
        cfg, ...
        'pcbAnalysisChannel', ...
        "C02");

    channelIndex = find( ...
        dataData.channels == channelName, ...
        1);

    if isempty(channelIndex)
        warning( ...
            'determineQuasiSteadyWindow:MissingPcbChannel', ...
            'Configured PCB analysis channel %s was not found.', ...
            channelName);
        return
    end

    signal = dataData.signal{channelIndex};
    time = dataData.time{channelIndex};

    if isempty(signal) || isempty(time) || ~isfinite(triggerTime)
        return
    end

    signal = signal(:);
    time = time(:);
    diagnostics.channel = channelName;
    diagnostics.time = time;

    fluctuationWindow = getTimingValue( ...
        cfg, ...
        'pcbFluctuationWindow', ...
        0.002);

    referenceDuration = getTimingValue( ...
        cfg, ...
        'pcbReferenceDuration', ...
        0.050);

    referenceGap = getTimingValue( ...
        cfg, ...
        'pcbReferenceGap', ...
        0.010);

    moderateLowerRatio = getTimingValue( ...
        cfg, ...
        'pcbModerateLowerRatio', ...
        1.5);

    unstartRatio = getTimingValue( ...
        cfg, ...
        'pcbUnstartRatio', ...
        4.0);

    minimumStartDuration = getTimingValue( ...
        cfg, ...
        'pcbMinimumStartDuration', ...
        0.050);

    unstartHoldTime = getTimingValue( ...
        cfg, ...
        'pcbUnstartHoldTime', ...
        0.020);

    fluctuationSamples = max( ...
        3, ...
        round(fluctuationWindow * dataData.samplingRate));

    fluctuationLevel = movstd( ...
        signal, ...
        fluctuationSamples, ...
        'omitnan');

    referenceEnd = triggerTime - referenceGap;
    referenceStart = referenceEnd - referenceDuration;

    referenceMask = ...
        time >= referenceStart & ...
        time <= referenceEnd;

    referenceLevel = median( ...
        fluctuationLevel(referenceMask), ...
        'omitnan');

    if ~isfinite(referenceLevel) || referenceLevel <= 0
        return
    end

    fluctuationRatio = fluctuationLevel / referenceLevel;
    pcbState = repmat("little", size(time));
    pcbState(fluctuationRatio >= moderateLowerRatio) = "some";
    pcbState(fluctuationRatio >= unstartRatio) = "lot";

    diagnostics.fluctuationLevel = fluctuationLevel;
    diagnostics.fluctuationRatio = fluctuationRatio;
    diagnostics.state = pcbState;
    diagnostics.referenceLevel = referenceLevel;

    firstValidStart = findFirstPcbStart( ...
    time, ...
    pcbState, ...
    triggerTime, ...
    minimumStartDuration);

    diagnostics.firstValidStart = firstValidStart;

    if ~isfinite(firstValidStart)
        return
    end

    unstartMask = ...
        time > firstValidStart & ...
        pcbState == "lot";

    unstartIndex = findFirstTrueRun( ...
        unstartMask, ...
        time, ...
        unstartHoldTime, ...
        1);

    if ~isfinite(unstartIndex)
        return
    end

    firstUnstart = time(unstartIndex);
    diagnostics.firstUnstart = firstUnstart;
    pcbWindow.startTime = firstValidStart;
    pcbWindow.endTime = firstUnstart;
    pcbWindow.valid = firstUnstart > firstValidStart;
end

function firstStartTime = findFirstPcbStart( ...
    time, pcbState, triggerTime, minimumDuration)

    firstStartTime = NaN;

    time = time(:);
    pcbState = pcbState(:);
    candidateMask = time >= triggerTime & pcbState == "some";

    % Search every continuous run, including those after rejected short runs.
    transitions = diff([false; candidateMask; false]);
    runStarts = find(transitions == 1);
    runEnds = find(transitions == -1) - 1;

    for runIndex = 1:numel(runStarts)
        firstIndex = runStarts(runIndex);
        lastIndex = runEnds(runIndex);

        if time(lastIndex) - time(firstIndex) >= minimumDuration
            firstStartTime = time(firstIndex);
            return
        end
    end
end

function index = findFirstTrueRun( ...
    mask, time, requiredDuration, startIndex)

    index = NaN;

    for candidateIndex = startIndex:numel(mask)

        if ~mask(candidateIndex)
            continue
        end

        endIndex = candidateIndex;

        while endIndex < numel(mask) && ...
                time(endIndex) - time(candidateIndex) < requiredDuration
            endIndex = endIndex + 1;
        end

        if time(endIndex) - time(candidateIndex) >= requiredDuration && ...
                all(mask(candidateIndex:endIndex))
            index = candidateIndex;
            return
        end
    end
end
