function reportSecondMode(~, secondModeResults)
    % REPORTSECONDMODE Prints a compact channel-by-channel report.
    numberOfChannels = numel(secondModeResults.channels);

    fprintf('\n');
    fprintf('Second-mode summary\n');
    fprintf('%s\n', repmat('-', 1, 96));
    fprintf('%-8s %-10s %11s %11s %10s %9s %10s %12s %12s\n', ...
        'Channel', 'Location', 'Median (kHz)', 'Mean (kHz)', 'Std (kHz)', ...
        'Valid (%)', 'Contrast', 'Appear (s)', 'Disappear (s)');
    fprintf('%s\n', repmat('-', 1, 96));

    for channelIndex = 1:numberOfChannels
        contrast = secondModeResults.peakContrast{channelIndex};

        if isempty(contrast)
            medianContrast = NaN;
        else
            medianContrast = median(contrast, 'omitnan');
        end

        fprintf('%-8s %-10s %11.2f %11.2f %10.2f %9.1f %10.2f %12.4f %12.4f\n', ...
            string(secondModeResults.channels(channelIndex)), ...
            string(secondModeResults.locations(channelIndex)), ...
            secondModeResults.frequencyMedian(channelIndex) / 1e3, ...
            secondModeResults.frequencyMean(channelIndex) / 1e3, ...
            secondModeResults.frequencyStd(channelIndex) / 1e3, ...
            secondModeResults.validFraction(channelIndex) * 100, ...
            medianContrast, ...
            secondModeResults.appearanceTime(channelIndex), ...
            secondModeResults.disappearanceTime(channelIndex));
    end

    fprintf('%s\n', repmat('-', 1, 96));
end