function reportSecondMode(~, secondModeResults)
    % REPORTSECONDMODE Prints a compact channel-by-channel report.
    numberOfChannels = numel(secondModeResults.channels);

    fprintf('\n');
    fprintf('Second-mode summary\n');
    fprintf('%s\n', repmat('-', 1, 96));
    fprintf('%-8s %-10s %11s %11s %10s %9s %10s %12s %12s %18s\n', ...
        'Channel', 'Location', 'Median (kHz)', 'Mean (kHz)', 'Std (kHz)', ...
        'Valid (%)', 'Contrast', 'Appear (s)', 'Disappear (s)', 'Final state');
    fprintf('%s\n', repmat('-', 1, 96));

    for channelIndex = 1:numberOfChannels
        contrast = secondModeResults.peakContrast{channelIndex};

        if isempty(contrast)
            medianContrast = NaN;
        else
            modePresent = secondModeResults.modePresent{channelIndex};
            medianContrast = median( ...
                contrast(modePresent), ...
                'omitnan');
        end

        modePresent = secondModeResults.modePresent{channelIndex};
        if ~any(modePresent)
            finalState = "never-established";
        elseif isfinite(secondModeResults.disappearanceTime(channelIndex))
            finalState = "mode-lost";
        else
            finalState = "present-through-record";
        end

        fprintf('%-8s %-10s %11.2f %11.2f %10.2f %9.1f %10.2f %12.4f %12.4f %18s\n', ...
            string(secondModeResults.channels(channelIndex)), ...
            string(secondModeResults.locations(channelIndex)), ...
            secondModeResults.frequencyMedian(channelIndex) / 1e3, ...
            secondModeResults.frequencyMean(channelIndex) / 1e3, ...
            secondModeResults.frequencyStd(channelIndex) / 1e3, ...
            secondModeResults.validFraction(channelIndex) * 100, ...
            medianContrast, ...
            secondModeResults.appearanceTime(channelIndex), ...
            secondModeResults.disappearanceTime(channelIndex), ...
            finalState);

        if isfield(secondModeResults, 'broadCandidate')
            broad = secondModeResults.broadCandidate{channelIndex};
            candidateValid = secondModeResults.candidateValid{channelIndex};
            contrastEligible = ...
                secondModeResults.contrastEligible{channelIndex};
            edgeEligible = secondModeResults.edgeEligible{channelIndex};
            stateValid = secondModeResults.stateValid{channelIndex};

            fprintf(['  Diagnostics: broad=%d, contrast=%d, edge=%d, ', ...
                'candidate=%d, state=%d\n'], ...
                nnz(broad), ...
                nnz(broad & contrastEligible), ...
                nnz(broad & edgeEligible), ...
                nnz(candidateValid), ...
                nnz(stateValid));
        end
    end

    fprintf('%s\n', repmat('-', 1, 96));
end