function validatePcbConfig(cfg)
%VALIDATEPCBCONFIG Validate a complete PCB workflow configuration.

requiredTopLevel = ["input", "conversion", "paths", "channels", ...
    "run", "analysis", "timing", "plotting", "spectrogram", ...
    "psd", "secondMode", "output"];
requireFields(cfg, requiredTopLevel, "cfg");

requireFields(cfg.input, ...
    ["source", "rawFolder", "rawFileName", "file", "variable"], ...
    "cfg.input");
requireFields(cfg.conversion, "mode", "cfg.conversion");
requireFields(cfg.paths, "additionalFolders", "cfg.paths");
requireFields(cfg.channels, ["recorderLabels", "maxPerRecorder", ...
    "driver", "trigger", "data", "driverSamplingRate", ...
    "triggerSamplingRate", "dataSamplingRate"], "cfg.channels");
requireFields(cfg.run, ["fullTracePlots", "quasiSteadyTracePlots", ...
    "steadySpectrogram", "fullSpectrogram", "spectrogramPlots", ...
    "windowedPsd", "windowedPsdPreview", "secondModeAnalysis", ...
    "saveResults", "closeFiguresAtStart"], "cfg.run");
requireFields(cfg.analysis, ["interval", "manualTimeRange", ...
    "onInvalidQuasiSteadyWindow"], "cfg.analysis");
requireFields(cfg.timing, ["triggerThreshold", "triggerHysteresis", ...
    "triggerHoldTime", "driverFlatWindow", "driverFlatHoldTime", ...
    "driverFlatEvaluationInterval", "driverFlatSlopeThreshold", ...
    "driverFlatNoiseThreshold", "driverDescendingSlopeThreshold", ...
    "pcbAnalysisChannel", "pcbFluctuationWindow", ...
    "pcbReferenceDuration", "pcbReferenceGap", ...
    "pcbMinimumStartDuration", "pcbUnstartHoldTime", ...
    "pcbModerateLowerRatio", "pcbUnstartRatio"], "cfg.timing");
requireFields(cfg.plotting, ...
    ["fontSize", "smoothData", "figurePosition"], ...
    "cfg.plotting");
requireFields(cfg.spectrogram, ...
    ["windowLength", "overlap", "frequencyBand", "colormap"], ...
    "cfg.spectrogram");
requireFields(cfg.psd, ["windowDuration", "windowStep", ...
    "welchSegmentDuration", "welchOverlap", "detrend", ...
    "plotFrequencyBand", "previewWindowIndices"], "cfg.psd");
requireFields(cfg.secondMode, ["channelsExcluded", "frequencyBand", ...
    "minimumProminenceDb", "minimumWidth", "fitHalfWidth"], ...
    "cfg.secondMode");
requireFields(cfg.output, ["rootFolder", "convertedDataFolder", ...
    "tracePlotFolder", "spectrogramFolder", "windowedPsdFolder", ...
    "resultsFile", "saveTracePlots", "saveSpectrogramData", ...
    "saveSpectrogramPlots", "saveWindowedPsdPlots", ...
    "saveRawPcbDataInResults"], "cfg.output");

source = string(cfg.input.source);
if ~isscalar(source) || ~ismember(source, ["pnrf", "mat"])
    error('validatePcbConfig:InvalidInputSource', ...
        'cfg.input.source must be "pnrf" or "mat".');
end

if source == "mat"
    if ~isfile(cfg.input.file)
        error('validatePcbConfig:InputFileNotFound', ...
            'MAT input file not found: %s', cfg.input.file);
    end
else
    if ~isfolder(cfg.input.rawFolder)
        error('validatePcbConfig:RawFolderNotFound', ...
            'PNRF folder not found: %s', cfg.input.rawFolder);
    end
    rawFile = fullfile(cfg.input.rawFolder, cfg.input.rawFileName);
    if ~isfile(rawFile)
        error('validatePcbConfig:RawFileNotFound', ...
            'PNRF input file not found: %s', rawFile);
    end
end

mode = string(cfg.conversion.mode);
if ~isscalar(mode) || ~ismember(mode, ["memory", "disk"])
    error('validatePcbConfig:InvalidConversionMode', ...
        'cfg.conversion.mode must be "memory" or "disk".');
end

recorderLabels = string(cfg.channels.recorderLabels(:));
if isempty(recorderLabels) || ...
        numel(unique(recorderLabels)) ~= numel(recorderLabels)
    error('validatePcbConfig:InvalidRecorderLabels', ...
        'Recorder labels must be nonempty and unique.');
end
if ~isPositiveInteger(cfg.channels.maxPerRecorder)
    error('validatePcbConfig:InvalidMaxPerRecorder', ...
        'cfg.channels.maxPerRecorder must be a positive integer.');
end

driver = string(cfg.channels.driver);
trigger = string(cfg.channels.trigger(:));
dataChannels = string(cfg.channels.data(:));
if ~isscalar(driver) || driver == "" || isempty(trigger) || ...
        isempty(dataChannels) || ...
        numel(unique(dataChannels)) ~= numel(dataChannels)
    error('validatePcbConfig:InvalidChannels', ...
        'Driver, trigger, and unique data channels are required.');
end

samplingRates = [cfg.channels.driverSamplingRate, ...
    cfg.channels.triggerSamplingRate, cfg.channels.dataSamplingRate];
if any(~isfinite(samplingRates)) || any(samplingRates <= 0)
    error('validatePcbConfig:InvalidSamplingRate', ...
        'All configured sampling rates must be positive.');
end

runFields = fieldnames(cfg.run);
for index = 1:numel(runFields)
    value = cfg.run.(runFields{index});
    if ~isscalar(value) || ~(islogical(value) || ...
            (isnumeric(value) && ismember(value, [0 1])))
        error('validatePcbConfig:InvalidRunSwitch', ...
            'cfg.run.%s must be true or false.', runFields{index});
    end
end

outputSwitches = ["saveTracePlots", "saveSpectrogramData", ...
    "saveSpectrogramPlots", "saveWindowedPsdPlots", ...
    "saveRawPcbDataInResults"];
for fieldName = outputSwitches
    value = cfg.output.(fieldName);
    if ~isscalar(value) || ~(islogical(value) || ...
            (isnumeric(value) && ismember(value, [0 1])))
        error('validatePcbConfig:InvalidOutputSwitch', ...
            'cfg.output.%s must be true or false.', fieldName);
    end
end

interval = string(cfg.analysis.interval);
if ~isscalar(interval) || ...
        ~ismember(interval, ["quasiSteady", "full", "manual"])
    error('validatePcbConfig:InvalidInterval', ...
        'cfg.analysis.interval must be "quasiSteady", "full", or "manual".');
end
if numel(cfg.analysis.manualTimeRange) ~= 2 || ...
        any(~isfinite(cfg.analysis.manualTimeRange)) || ...
        cfg.analysis.manualTimeRange(2) <= cfg.analysis.manualTimeRange(1)
    error('validatePcbConfig:InvalidManualRange', ...
        'cfg.analysis.manualTimeRange must be [start end] in seconds.');
end
failureMode = string(cfg.analysis.onInvalidQuasiSteadyWindow);
if ~isscalar(failureMode) || ...
        ~ismember(failureMode, ["useFullRecord", "error"])
    error('validatePcbConfig:InvalidFailureMode', ...
        ['cfg.analysis.onInvalidQuasiSteadyWindow must be ', ...
        '"useFullRecord" or "error".']);
end

if ~ismember(string(cfg.timing.pcbAnalysisChannel), dataChannels)
    error('validatePcbConfig:InvalidTimingChannel', ...
        'cfg.timing.pcbAnalysisChannel must be in cfg.channels.data.');
end

timingFields = setdiff(string(fieldnames(cfg.timing)), ...
    "pcbAnalysisChannel");
for fieldName = timingFields.'
    value = cfg.timing.(fieldName);
    if ~isscalar(value) || ~isnumeric(value) || ~isfinite(value)
        error('validatePcbConfig:InvalidTimingSetting', ...
            'cfg.timing.%s must be a finite numeric scalar.', fieldName);
    end
end

positiveTimingFields = ["triggerHoldTime", "driverFlatWindow", ...
    "driverFlatHoldTime", "driverFlatEvaluationInterval", ...
    "pcbFluctuationWindow", "pcbReferenceDuration", ...
    "pcbReferenceGap", "pcbMinimumStartDuration", ...
    "pcbUnstartHoldTime", "pcbModerateLowerRatio", ...
    "pcbUnstartRatio"];
for fieldName = positiveTimingFields
    if cfg.timing.(fieldName) <= 0
        error('validatePcbConfig:InvalidTimingSetting', ...
            'cfg.timing.%s must be positive.', fieldName);
    end
end

validateBand(cfg.spectrogram.frequencyBand, ...
    cfg.channels.dataSamplingRate, 'cfg.spectrogram.frequencyBand');
validateBand(cfg.psd.plotFrequencyBand, ...
    cfg.channels.dataSamplingRate, 'cfg.psd.plotFrequencyBand');
validateBand(cfg.secondMode.frequencyBand, ...
    cfg.channels.dataSamplingRate, 'cfg.secondMode.frequencyBand');

if ~isPositiveInteger(cfg.spectrogram.windowLength) || ...
        ~isFraction(cfg.spectrogram.overlap)
    error('validatePcbConfig:InvalidSpectrogram', ...
        'Spectrogram window length and overlap are invalid.');
end
if cfg.psd.windowDuration <= 0 || cfg.psd.windowStep <= 0 || ...
        cfg.psd.welchSegmentDuration <= 0 || ...
        cfg.psd.welchSegmentDuration > cfg.psd.windowDuration || ...
        ~isFraction(cfg.psd.welchOverlap)
    error('validatePcbConfig:InvalidPsd', ...
        'Windowed PSD durations or overlap are invalid.');
end
if ~isscalar(string(cfg.psd.detrend)) || ...
        ~ismember(string(cfg.psd.detrend), ...
        ["linear", "constant", "none"])
    error('validatePcbConfig:InvalidDetrend', ...
        'cfg.psd.detrend must be "linear", "constant", or "none".');
end

previewIndices = cfg.psd.previewWindowIndices;
if ~(isstring(previewIndices) && isscalar(previewIndices) && ...
        previewIndices == "all") && ...
        ~(isnumeric(previewIndices) && all(previewIndices >= 1) && ...
        all(previewIndices == fix(previewIndices)))
    error('validatePcbConfig:InvalidPreviewIndices', ...
        'cfg.psd.previewWindowIndices must be "all" or positive integers.');
end

excluded = string(cfg.secondMode.channelsExcluded(:));
excluded(excluded == "") = [];
unknownExcluded = setdiff(excluded, dataChannels);
if ~isempty(unknownExcluded)
    error('validatePcbConfig:UnknownExcludedChannel', ...
        'Excluded channel(s) not selected as data: %s', ...
        strjoin(unknownExcluded, ", "));
end
if cfg.secondMode.minimumProminenceDb < 0 || ...
        cfg.secondMode.minimumWidth < 0 || ...
        cfg.secondMode.fitHalfWidth <= 0
    error('validatePcbConfig:InvalidSecondModeSettings', ...
        'Second-mode prominence, width, and fit settings are invalid.');
end

additionalFolders = string(cfg.paths.additionalFolders(:));
additionalFolders(additionalFolders == "") = [];
for folder = additionalFolders.'
    if ~isfolder(folder)
        error('validatePcbConfig:AdditionalFolderNotFound', ...
            'Additional MATLAB folder not found: %s', folder);
    end
end
end

function requireFields(value, fieldNames, parentName)
for fieldName = string(fieldNames)
    if ~isfield(value, fieldName)
        error('validatePcbConfig:MissingField', ...
            'Required configuration field is missing: %s.%s', ...
            parentName, fieldName);
    end
end
end

function tf = isPositiveInteger(value)
tf = isscalar(value) && isfinite(value) && value >= 1 && value == fix(value);
end

function tf = isFraction(value)
tf = isscalar(value) && isfinite(value) && value >= 0 && value < 1;
end

function validateBand(band, samplingRate, name)
if numel(band) ~= 2 || any(~isfinite(band)) || band(1) < 0 || ...
        band(2) <= band(1) || band(2) > samplingRate / 2
    error('validatePcbConfig:InvalidFrequencyBand', ...
        '%s must be increasing and within [0, Nyquist].', name);
end
end
