function formatAxes(xLabelText, yLabelText, fontsize)
    if nargin < 3
        fontsize = 12; % default font size
    end

    hXLabel = xlabel(xLabelText, 'Interpreter', 'latex');
    hYLabel = ylabel(yLabelText, 'Interpreter', 'latex');

    set(gcf, 'Color', 'w');
    set(gca, ...
        'FontName', 'Times', ...
        'FontSize', fontsize, ...
        'Box', 'on', ...
        'LineWidth', 1, ...
        'TickDir', 'in', ...
        'TickLength', [0.01 0.01], ...
        'XMinorTick', 'on', ...
        'YMinorTick', 'on', ...
        'YGrid', 'on', ...
        'Layer', 'top');
    
    set([hXLabel, hYLabel], 'FontName', 'Times', 'FontSize', fontsize);
    
    ax = gca;
    ax.GridLineStyle = '-';
    
    grid on;
    view(2);
    box on;
end